<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

| **Term**     |  **Brief Description**  |
| :--- | :--: |
| Subsetting   |  It refers to the utilisation of only a subsection of a list or array, instead of the entire data collection, in functions. |
| Indexing   |  It is a form of subsetting, in which a single element in a list/array is used in a called function. (e.g. list[1])  |
| Slicing   |  It is a form of subsetting, in which a range of elements in a list/array is used in a called function. (e.g. list[1:4]) | 
| Masking   |  When given a condition to follow, elements will return Boolean values of "True" or 'False'. The elements can then be sieved, such that all elements that satisfy that condiiton, and return a "True" value, will be shown in the array and used for downstream functions. On the other hand, elements that do not satisfy the condition are not shown in the array and will not be used in functions. (e.g np.array[mask] to only contain elements that satisfy the condition)

## Exercise 2

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

First_elements = np_array_2d[: , 0]                         # To create a subset of the first elements
print(First_elements)                                       # Print function is used just to show the change in arrays

Integer = First_elements.astype(int)                        # To change the elements into integer form
print(Integer)

Binary_array = Integer%2                                    # To calculate the remainder of each element to determine if it's even or odd
print(Binary_array)

mask = Binary_array == 1                                    # To choose elements that are 1
print(mask)

Letter_array = np_array_2d[mask]                            # To choose the pairs that have 1 as their first element
print(Letter_array[: , 1])                                  # To select the second element 


['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']
[ 1  3  2  4  5  7  6  8 10  9]
[1 1 0 0 1 1 0 0 0 1]
[ True  True False False  True  True False False False  True]
['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [ ]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]) 
                                                                # Since there are no values below 50, I can start to modify the other values
AboveFifty = np_array > 50
np_array[AboveFifty] = 1                                        # Takes all values that give "True" and changes them to one

EqualFifty = np_array == 50
np_array[EqualFifty] = 0                                        # Takes all values that give "True" and changes them to zero
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
