<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [3]:
py_list

['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']

In [4]:
py_list[2]

'c3'

In [9]:
py_list[2:5] # the slicing process of python ends with x-1 (in this case, the element corresponding to 5-1)

['c3', 'd4', 'e5']

In [11]:
py_list[1:6] # 5 elements will be chosen

['b2', 'c3', 'd4', 'e5', 'f6']

In [12]:
py_list[1:6:2] # moves in steps of 2

['b2', 'd4', 'f6']

In [13]:
py_list[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

In [14]:
py_list[2:5:-1]

[]

In [15]:
py_list[5:2:-1]

['f6', 'e5', 'd4']

In [ ]:
py_list[::-1] #indicates "go from the start and to the end, starting from the last element". 
              #way of writing the elements in reeverse

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

In [16]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [17]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = np_array % 3 == 0
np_array[mask]

array([3, 6, 9])

In [21]:
mask #acts as a true/false statement, only adds those that are true

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [22]:
mask.sum() #number of trues

np.int64(3)

In [18]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np_array//2 # Quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [20]:
np_array%2 # Remainder

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [23]:
np_array[~mask]

array([ 1,  2,  4,  5,  7,  8, 10])

In [24]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND' , remember to put brackets when using &

array([4, 5, 6, 7])

In [27]:
np.logical_and(np_array>3,np_array<8) #same as above

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [26]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [28]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [31]:
print(py_list_2d[3][1])
print(py_list_2d[3][0])

D
4


In [36]:
py_list_2d[3:]

[[4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J']]

In [37]:
py_list_2d[3:][0]

[4, 'D']

In [32]:
np_array_2d[3,0] #Only for numpy

np.str_('4')

In [35]:
np_array_2d[:3,1] #only for Numpy

array(['A', 'B', 'C'], dtype='<U21')

In [38]:
np_array_2d[:3,1] #only for Numpy

array(['A', 'B', 'C'], dtype='<U21')

## 1.4 Growing lists

In [39]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [42]:
x=[1,2] + [3]
print(x)
x= x + [4]
print(x)
x= x + [5]
print(x)
x= x + [6]
print(x)
x

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]

In [41]:
x=[1,2] + [3]
print(x)
x+= x + [4]
print(x)
x+= x + [5]
print(x)
x+= x + [6]
print(x)
x+= x + [7]
print(x)
x

[1, 2, 3]
[1, 2, 3, 1, 2, 3, 4]
[1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5]
[1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5, 1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5, 1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5, 6, 1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5, 1, 2, 3, 1, 2, 3, 4, 1, 2, 3, 1, 2, 3, 4, 5, 6, 7]


[1,
 2,
 3,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 5,
 6,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 1,
 2,
 3,
 4,
 5,
 6,
 7]

In [43]:
x=[1,2]                             #same answer as above but implemented differently, also append is faster
print(x)
x.append(4)

print(x)
x.append(5)
print(x)
x.append(6)
print(x)
x.append(7)
print(x)
x

[1, 2]
[1, 2, 4]
[1, 2, 4, 5]
[1, 2, 4, 5, 6]
[1, 2, 4, 5, 6, 7]


[1, 2, 4, 5, 6, 7]

In [44]:
a={1,2,3}
b=[1,2,3]

In [ ]:
a + [1] # doesnt work as tuples cannot be changed

TypeError: unsupported operand type(s) for +: 'set' and 'list'

In [46]:
b + [1]

[1, 2, 3, 1]

In [48]:
x = [1,2,3]
y=x
z=x

In [49]:
print(f'{x=}',f'{y=}',f'{z=}')

x=[1, 2, 3] y=[1, 2, 3] z=[1, 2, 3]


In [52]:
x.append(1)
print(f'{x=}',f'{y=}',f'{z=}')

x=[1, 2, 3, 1, 1] y=[1, 2, 3, 1, 1] z=[1, 2, 3, 1, 1]


In [ ]:
x.append(1)
z.append(1000)                              #adds 1000 to everything, acts as though x,y,z are the same
print(f'{x=}',f'{y=}',f'{z=}')

x=[1, 2, 3, 1, 1, 1, 1000] y=[1, 2, 3, 1, 1, 1, 1000] z=[1, 2, 3, 1, 1, 1, 1000]


In [54]:
x = [1,2,3]
y=x.copy()
z=x.copy()

In [ ]:
x.append(1)
z.append(1000)                              #now it will only add to 1000 to z
print(f'{x=}',f'{y=}',f'{z=}')

x=[1, 2, 3, 1] y=[1, 2, 3] z=[1, 2, 3, 1000]


# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes