<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [ ]:
import numpy as np

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
# py is put in the name to indicate that its a python list

In [ ]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [5]:
py_real_names[0]
# elements start from 0

'Natasha Romanoff'

In [6]:
py_super_names[0]

'Black Widow'

In [12]:
i=0
print(py_real_names[i],'is', py_super_names[i])

Natasha Romanoff is Black Widow


In [9]:
py_super_names[2]

'Doctor Strange'

In [10]:
py_super_names[-1]
# the negative sign indicates a movement starting from the end of the list

'Doctor Strange'

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

In [13]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

superhero_info["Peter Parker"]= "Spiderman" 
superhero_info

{'Natasha Romanoff': 'Black Widow',
 'Tony Stark': 'Iron Man',
 'Stephen Strange': 'Doctor Strange',
 'Peter Parker': 'Spiderman'}

In [14]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange', 'Peter Parker'])

In [15]:
superhero_info.values()


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'Spiderman'])

## 1.4 Higher dimensional lists

In [ ]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
# contains lists within lists

py_superhero_info[-1][-1]
# first bracket relates to list number, second bracket relates to element number within selected list

'Doctor Strange'

# 2 Lists vs. Arrays

In [23]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list (recast data from python list into numpy array)
                                        # to create a NEW
                                        # NumPy array

In [24]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [27]:
print(np_array_2d)

print( "The numbers become strings")

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]
The numbers become strings


## 2.1 Size

In [31]:
len(py_list_2d)



10

In [32]:
len(np_array_2d)

10

In [ ]:
np_array_2d.size
# includes elements within array

20

In [34]:
py_list_2d = [[1, "A","a"], [2, "B","b"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

The above happens as numpy is very picky about type and size (must be consistent and aligned throughout), while the change is accepted by python

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

In [35]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [36]:
py_list

[1, 2, 3, 4, 5]

In [37]:
np_array

array([1, 2, 3, 4, 5])

In [39]:
py_list+100

TypeError: can only concatenate list (not "int") to list

In [40]:
np_array+100


array([101, 102, 103, 104, 105])

Above occurs as 100 is not defined for python, since python lists can be of any size/arrangement

In [44]:
py_list +[100]

[1, 2, 3, 4, 5, 100]

## 2.4 Adding another list

In [43]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(np_array_1, np_array_2 , sep='\n')

[1 2 3 4 5]
[10 20 30 40 50]


In [45]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [46]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [48]:
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [49]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [51]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [52]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [53]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [54]:
py_list == 3     # Works, but what IS the question?
np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

In [55]:
py_list == 3     # Works, but what IS the question?
 
py_list > 3  

TypeError: '>' not supported between instances of 'list' and 'int'

In [56]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [57]:
np_array

array([1, 2, 3, 4, 5])

In [58]:
np_array==3

array([False, False,  True, False, False])

In [59]:
np_array>3


array([False, False, False,  True,  True])

In [64]:
sum(np_array>3) # only counts the number of "True" present
sum([False, False, False,  True,  True])

2

In [ ]:
mask = np_array > 3 # this process is known as masking (picks out the elements that are greater than 3)
np_array[mask].sum()

np.int64(9)

In [ ]:
py_list = [1,2,3,4,5]*10

np_arra

## 2.8 Mathematics

In [66]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [72]:
print(sum(py_list))     # sum() is a base Python function
print(max(py_list))     # max() is a base Python function
print(min(py_list))     # min() is a base Python function
print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())

15
5
1
15
5
1
3.0
1.4142135623730951


In [68]:
sum(py_list)/len(py_list) # in order to find mean via python lists

3.0

In [69]:
np_array.mean()

np.float64(3.0)

In [70]:
np.median(np_array)

np.float64(3.0)

In [71]:
np_array.std()

np.float64(1.4142135623730951)

## Footnotes

1. Numpy arrays are used for mathematical purposes
1. Both python lists and numpy arrays are good ways of storing data, and can be converted from one form to another
1. Numpy arrays a bit picky 